name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('src/**/*.gradle*', 'src/gradle/libs.versions.toml') }}

      - name: Grant permission
        run: chmod +x src/gradlew

      - name: Build
        run: cd src && ./gradlew build

      - name: Run Tests
        run: cd src && ./gradlew test